package controllergen

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	json "encoding/json"
	"github.com/gorilla/mux"
	controller "github.com/mh-cbon/ggt/ademo/controller"
	model "github.com/mh-cbon/ggt/ademo/model"
	ggt "github.com/mh-cbon/ggt/lib"
	"io"
	"net/http"
	"strconv"
)

var xxStrconvAtoi = strconv.Atoi
var xxIoCopy = io.Copy
var xxHTTPOk = http.StatusOK

// TomatesController is an httper of Tomates.
// Tomates controller.
type TomatesController struct {
	embed controller.Tomates
}

// NewTomatesController constructs an httper of Tomates
func NewTomatesController(embed controller.Tomates) *TomatesController {
	ret := &TomatesController{
		embed: embed,
	}
	return ret
}

// GetByID invoke Tomates.GetByID using the request body as a json payload.
// GetByID read the Tomate of given ID
func (t *TomatesController) GetByID(w http.ResponseWriter, r *http.Request) {

	xxURLValues := r.URL.Query()
	var getID string
	if _, ok := xxURLValues["id"]; ok {
		xxTmpgetID := xxURLValues.Get("id")
		getID = xxTmpgetID
	}

	jsonResBody, err := t.embed.GetByID(getID)

	if err != nil {

		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

}

// Create invoke Tomates.Create using the request body as a json payload.
// Create a new Tomate
func (t *TomatesController) Create(w http.ResponseWriter, r *http.Request) {

	{
		err := r.ParseForm()

		if err != nil {

			t.embed.Finalizer(w, r, err)

			return
		}

	}
	var postColor *string
	if _, ok := r.Form["color"]; ok {
		xxTmppostColor := r.FormValue("color")
		postColor = &xxTmppostColor
	}

	jsonResBody, err := t.embed.Create(postColor)

	if err != nil {

		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

}

// Update invoke Tomates.Update using the request body as a json payload.
// Update an existing Tomate
//
// @route /write/{id:[0-9]+}
func (t *TomatesController) Update(w http.ResponseWriter, r *http.Request) {

	xxRouteVars := mux.Vars(r)
	var routeID string
	if _, ok := xxRouteVars["id"]; ok {
		xxTmprouteID := xxRouteVars["id"]
		routeID = xxTmprouteID
	}
	var jsonReqBody *model.Tomate
	{
		jsonReqBody = &model.Tomate{}
		decErr := json.NewDecoder(r.Body).Decode(jsonReqBody)

		if decErr != nil {

			t.embed.Finalizer(w, r, decErr)

			return
		}

		defer r.Body.Close()
	}

	jsonResBody, err := t.embed.Update(routeID, jsonReqBody)

	if err != nil {

		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

}

// TomatesControllerMethodSet providers the methods set of a *TomatesController
func TomatesControllerMethodSet(t *TomatesController) ggt.MethodSet {
	var ret = ggt.NewMethodSet()

	ret = ret.Register(func(x interface{}) http.HandlerFunc { return x.(*TomatesController).GetByID }, "GetByID", "GetByID", []string{})

	ret = ret.Register(func(x interface{}) http.HandlerFunc { return x.(*TomatesController).Create }, "Create", "Create", []string{})

	ret = ret.Register(func(x interface{}) http.HandlerFunc { return x.(*TomatesController).Update }, "Update", "/write/{id:[0-9]+}", []string{})

	return ret
}
