package capable

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	"context"
	ggt "github.com/mh-cbon/ggt/lib"
	finder "github.com/mh-cbon/service-finder"
	"io"
	"net/http"
	"strconv"
)

var xxbf59c35679833d07f3bb2c9dae4379d8bcde018a = strconv.Atoi
var xx1991daf9713fb8fe63416b8e9da8f42837241f3e = io.Copy
var xx241e5271752059ff147549db36792098f0df9b88 = http.StatusOK

// RPCCtx is an httper of Ctx.
// Ctx ...
type RPCCtx struct {
	embed    Ctx
	Services finder.ServiceFinder
	Log      ggt.HTTPLogger
	Session  ggt.SessionStoreProvider
	Upload   ggt.Uploader
}

// NewRPCCtx constructs an httper of Ctx
func NewRPCCtx(embed Ctx) *RPCCtx {
	ret := &RPCCtx{
		embed:    embed,
		Services: finder.New(),
		Log:      &ggt.VoidLog{},
		Session:  &ggt.VoidSession{},
		Upload:   &ggt.FileProvider{},
	}
	ret.Log.Handle(nil, nil, nil, "constructor", "RPCCtx")
	return ret
}

// Get invoke Ctx.Get using the request body as a json payload.
// Get the context
// @route get
func (t *RPCCtx) Get(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCCtx", "Get")

	reqCtx := r.Context()
	whatever := reqCtx

	t.embed.Get(whatever)

	w.WriteHeader(200)

	t.Log.Handle(w, r, nil, "end", "RPCCtx", "Get")

}

// GetOne invoke Ctx.GetOne using the request body as a json payload.
// GetOne arg from context.
// @route getone
func (t *RPCCtx) GetOne(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCCtx", "GetOne")

	reqCtx := r.Context()
	var ctxArg1 Whatever
	{
		ctxVal := reqCtx.Value("ggt.arg1")
		if ctxVal != nil {
			if x, ok := ctxVal.(Whatever); ok {
				ctxArg1 = x
			}
		}
	}

	t.embed.GetOne(ctxArg1)

	w.WriteHeader(200)

	t.Log.Handle(w, r, nil, "end", "RPCCtx", "GetOne")

}

// MaybeGetOne invoke Ctx.MaybeGetOne using the request body as a json payload.
// MaybeGetOne arg from the context
// @route maybegetone
func (t *RPCCtx) MaybeGetOne(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCCtx", "MaybeGetOne")

	reqCtx := r.Context()
	var ctxArg1 *Whatever
	{
		ctxVal := reqCtx.Value("ggt.arg1")
		if ctxVal != nil {
			if x, ok := ctxVal.(*Whatever); ok {
				ctxArg1 = x
			}
		}
	}

	t.embed.MaybeGetOne(ctxArg1)

	w.WriteHeader(200)

	t.Log.Handle(w, r, nil, "end", "RPCCtx", "MaybeGetOne")

}

// SetOne invoke Ctx.SetOne using the request body as a json payload.
// SetOne arg on the context.
// @route setone
func (t *RPCCtx) SetOne(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCCtx", "SetOne")

	reqCtx := r.Context()

	ctxArg1 := t.embed.SetOne()
	reqCtx = context.WithValue(reqCtx, "ggt.arg1", ctxArg1)

	r = r.WithContext(reqCtx)

	t.Log.Handle(w, r, nil, "end", "RPCCtx", "SetOne")

}

// MaybeSetOne invoke Ctx.MaybeSetOne using the request body as a json payload.
// MaybeSetOne arg on the context
// @route maybesetone
func (t *RPCCtx) MaybeSetOne(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCCtx", "MaybeSetOne")

	reqCtx := r.Context()

	ctxArg1 := t.embed.MaybeSetOne()
	reqCtx = context.WithValue(reqCtx, "ggt.arg1", ctxArg1)

	r = r.WithContext(reqCtx)

	t.Log.Handle(w, r, nil, "end", "RPCCtx", "MaybeSetOne")

}

// RPCCtxDescriptor describe a *RPCCtx
type RPCCtxDescriptor struct {
	ggt.TypeDescriptor
	about             *RPCCtx
	methodGet         *ggt.MethodDescriptor
	methodGetOne      *ggt.MethodDescriptor
	methodMaybeGetOne *ggt.MethodDescriptor
	methodSetOne      *ggt.MethodDescriptor
	methodMaybeSetOne *ggt.MethodDescriptor
}

// NewRPCCtxDescriptor describe a *RPCCtx
func NewRPCCtxDescriptor(about *RPCCtx) *RPCCtxDescriptor {
	ret := &RPCCtxDescriptor{about: about}
	ret.methodGet = &ggt.MethodDescriptor{
		Name:    "Get",
		Handler: about.Get,
		Route:   "get",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGet)
	ret.methodGetOne = &ggt.MethodDescriptor{
		Name:    "GetOne",
		Handler: about.GetOne,
		Route:   "getone",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGetOne)
	ret.methodMaybeGetOne = &ggt.MethodDescriptor{
		Name:    "MaybeGetOne",
		Handler: about.MaybeGetOne,
		Route:   "maybegetone",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodMaybeGetOne)
	ret.methodSetOne = &ggt.MethodDescriptor{
		Name:    "SetOne",
		Handler: about.SetOne,
		Route:   "setone",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodSetOne)
	ret.methodMaybeSetOne = &ggt.MethodDescriptor{
		Name:    "MaybeSetOne",
		Handler: about.MaybeSetOne,
		Route:   "maybesetone",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodMaybeSetOne)
	return ret
}

// Get returns a MethodDescriptor
func (t *RPCCtxDescriptor) Get() *ggt.MethodDescriptor { return t.methodGet }

// GetOne returns a MethodDescriptor
func (t *RPCCtxDescriptor) GetOne() *ggt.MethodDescriptor { return t.methodGetOne }

// MaybeGetOne returns a MethodDescriptor
func (t *RPCCtxDescriptor) MaybeGetOne() *ggt.MethodDescriptor { return t.methodMaybeGetOne }

// SetOne returns a MethodDescriptor
func (t *RPCCtxDescriptor) SetOne() *ggt.MethodDescriptor { return t.methodSetOne }

// MaybeSetOne returns a MethodDescriptor
func (t *RPCCtxDescriptor) MaybeSetOne() *ggt.MethodDescriptor { return t.methodMaybeSetOne }
