package capable

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	json "encoding/json"
	ggt "github.com/mh-cbon/ggt/lib"
	"io"
	"net/http"
	"strconv"
)

var xx13751970453540515f0a8d0c51a507240ddecd56 = strconv.Atoi
var xx2743bd9627cf02ff8344f4b5bfbc9d9e022bf80e = io.Copy
var xx481e43390eea17d2be9267c3a6b7f018b078d86c = http.StatusOK

// RPCRoute is an httper of Route.
// Route ...
type RPCRoute struct {
	embed Route
	Log   ggt.HTTPLogger
}

// NewRPCRoute constructs an httper of Route
func NewRPCRoute(embed Route) *RPCRoute {
	ret := &RPCRoute{
		embed: embed,
		Log:   &ggt.VoidLog{},
	}
	ret.Log.Handle(nil, nil, nil, "constructor", "RPCRoute")
	return ret
}

// GetAll invoke Route.GetAll using the request body as a json payload.
// GetAll ...
func (t *RPCRoute) GetAll(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCRoute", "GetAll")
	input := struct {
		Arg0 map[string]string
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCRoute", "GetAll")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetAll(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCRoute", "GetAll")
}

// GetOne invoke Route.GetOne using the request body as a json payload.
// GetOne ...
func (t *RPCRoute) GetOne(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCRoute", "GetOne")
	input := struct {
		Arg0 string
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCRoute", "GetOne")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetOne(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCRoute", "GetOne")
}

// GetMany invoke Route.GetMany using the request body as a json payload.
// GetMany ...
func (t *RPCRoute) GetMany(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCRoute", "GetMany")
	input := struct {
		Arg0 string
		Arg1 string
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCRoute", "GetMany")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetMany(input.Arg0, input.Arg1)

	t.Log.Handle(w, r, nil, "end", "RPCRoute", "GetMany")
}

// GetConvertedToInt invoke Route.GetConvertedToInt using the request body as a json payload.
// GetConvertedToInt ...
func (t *RPCRoute) GetConvertedToInt(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCRoute", "GetConvertedToInt")
	input := struct {
		Arg0 int
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCRoute", "GetConvertedToInt")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetConvertedToInt(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCRoute", "GetConvertedToInt")
}

// GetConvertedToBool invoke Route.GetConvertedToBool using the request body as a json payload.
// GetConvertedToBool ...
func (t *RPCRoute) GetConvertedToBool(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCRoute", "GetConvertedToBool")
	input := struct {
		Arg0 bool
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCRoute", "GetConvertedToBool")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetConvertedToBool(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCRoute", "GetConvertedToBool")
}

// GetMaybe invoke Route.GetMaybe using the request body as a json payload.
// GetMaybe ...
func (t *RPCRoute) GetMaybe(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCRoute", "GetMaybe")
	input := struct {
		Arg0 *string
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCRoute", "GetMaybe")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetMaybe(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCRoute", "GetMaybe")
}

// RPCRouteDescriptor describe a *RPCRoute
type RPCRouteDescriptor struct {
	ggt.TypeDescriptor
	about                    *RPCRoute
	methodGetAll             *ggt.MethodDescriptor
	methodGetOne             *ggt.MethodDescriptor
	methodGetMany            *ggt.MethodDescriptor
	methodGetConvertedToInt  *ggt.MethodDescriptor
	methodGetConvertedToBool *ggt.MethodDescriptor
	methodGetMaybe           *ggt.MethodDescriptor
}

// NewRPCRouteDescriptor describe a *RPCRoute
func NewRPCRouteDescriptor(about *RPCRoute) *RPCRouteDescriptor {
	ret := &RPCRouteDescriptor{about: about}
	ret.methodGetAll = &ggt.MethodDescriptor{
		Name:    "GetAll",
		Handler: about.GetAll,
		Route:   "GetAll",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGetAll)
	ret.methodGetOne = &ggt.MethodDescriptor{
		Name:    "GetOne",
		Handler: about.GetOne,
		Route:   "GetOne",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGetOne)
	ret.methodGetMany = &ggt.MethodDescriptor{
		Name:    "GetMany",
		Handler: about.GetMany,
		Route:   "GetMany",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGetMany)
	ret.methodGetConvertedToInt = &ggt.MethodDescriptor{
		Name:    "GetConvertedToInt",
		Handler: about.GetConvertedToInt,
		Route:   "GetConvertedToInt",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGetConvertedToInt)
	ret.methodGetConvertedToBool = &ggt.MethodDescriptor{
		Name:    "GetConvertedToBool",
		Handler: about.GetConvertedToBool,
		Route:   "GetConvertedToBool",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGetConvertedToBool)
	ret.methodGetMaybe = &ggt.MethodDescriptor{
		Name:    "GetMaybe",
		Handler: about.GetMaybe,
		Route:   "GetMaybe",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGetMaybe)
	return ret
}

// GetAll returns a MethodDescriptor
func (t *RPCRouteDescriptor) GetAll() *ggt.MethodDescriptor { return t.methodGetAll }

// GetOne returns a MethodDescriptor
func (t *RPCRouteDescriptor) GetOne() *ggt.MethodDescriptor { return t.methodGetOne }

// GetMany returns a MethodDescriptor
func (t *RPCRouteDescriptor) GetMany() *ggt.MethodDescriptor { return t.methodGetMany }

// GetConvertedToInt returns a MethodDescriptor
func (t *RPCRouteDescriptor) GetConvertedToInt() *ggt.MethodDescriptor {
	return t.methodGetConvertedToInt
}

// GetConvertedToBool returns a MethodDescriptor
func (t *RPCRouteDescriptor) GetConvertedToBool() *ggt.MethodDescriptor {
	return t.methodGetConvertedToBool
}

// GetMaybe returns a MethodDescriptor
func (t *RPCRouteDescriptor) GetMaybe() *ggt.MethodDescriptor { return t.methodGetMaybe }
