package capable

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	"github.com/gorilla/mux"
	ggt "github.com/mh-cbon/ggt/lib"
	"io"
	"net/http"
	"strconv"
)

var xxa93bea9b3161bdd94ae3d137e63b0a8681e9e7a7 = strconv.Atoi
var xx34995c941601fa6fe9e9e2281bb739c5ca3c4b98 = io.Copy
var xxafd96cb0b6a582f43bb5bb685964cbe68c65a47a = http.StatusOK

// RestReq is an httper of Req.
// Req ...
type RestReq struct {
	embed Req
	Log   ggt.HTTPLogger
}

// NewRestReq constructs an httper of Req
func NewRestReq(embed Req) *RestReq {
	ret := &RestReq{
		embed: embed,
		Log:   &ggt.VoidLog{},
	}
	ret.Log.Handle(nil, nil, nil, "constructor", "RestReq")
	return ret
}

// GetOne invoke Req.GetOne using the request body as a json payload.
// GetOne ...
func (t *RestReq) GetOne(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RestReq", "GetOne")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RestReq", "GetOne")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}

	xxRouteVars := mux.Vars(r)

	xxURLValues := r.URL.Query()
	var reqArg1 string
	if _, ok := xxRouteVars["arg1"]; ok {
		xxTmpreqArg1 := xxRouteVars["arg1"]
		reqArg1 = xxTmpreqArg1
	} else if _, ok := xxURLValues["arg1"]; ok {
		xxTmpreqArg1 := xxURLValues.Get("arg1")
		reqArg1 = xxTmpreqArg1
	} else if _, ok := r.Form["arg1"]; ok {
		xxTmpreqArg1 := r.FormValue("arg1")
		reqArg1 = xxTmpreqArg1
	}

	t.embed.GetOne(reqArg1)
	w.WriteHeader(200)

	t.Log.Handle(w, r, nil, "end", "RestReq", "GetOne")
}

// GetMany invoke Req.GetMany using the request body as a json payload.
// GetMany ...
func (t *RestReq) GetMany(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RestReq", "GetMany")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RestReq", "GetMany")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}

	xxRouteVars := mux.Vars(r)

	xxURLValues := r.URL.Query()
	var reqArg1 string
	if _, ok := xxRouteVars["arg1"]; ok {
		xxTmpreqArg1 := xxRouteVars["arg1"]
		reqArg1 = xxTmpreqArg1
	} else if _, ok := xxURLValues["arg1"]; ok {
		xxTmpreqArg1 := xxURLValues.Get("arg1")
		reqArg1 = xxTmpreqArg1
	} else if _, ok := r.Form["arg1"]; ok {
		xxTmpreqArg1 := r.FormValue("arg1")
		reqArg1 = xxTmpreqArg1
	}
	var reqArg2 string
	if _, ok := xxRouteVars["arg2"]; ok {
		xxTmpreqArg2 := xxRouteVars["arg2"]
		reqArg2 = xxTmpreqArg2
	} else if _, ok := xxURLValues["arg2"]; ok {
		xxTmpreqArg2 := xxURLValues.Get("arg2")
		reqArg2 = xxTmpreqArg2
	} else if _, ok := r.Form["arg2"]; ok {
		xxTmpreqArg2 := r.FormValue("arg2")
		reqArg2 = xxTmpreqArg2
	}

	t.embed.GetMany(reqArg1, reqArg2)
	w.WriteHeader(200)

	t.Log.Handle(w, r, nil, "end", "RestReq", "GetMany")
}

// GetConvertedToInt invoke Req.GetConvertedToInt using the request body as a json payload.
// GetConvertedToInt ...
func (t *RestReq) GetConvertedToInt(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RestReq", "GetConvertedToInt")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RestReq", "GetConvertedToInt")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}

	xxRouteVars := mux.Vars(r)

	xxURLValues := r.URL.Query()
	var reqArg1 int
	if _, ok := xxRouteVars["arg1"]; ok {
		xxTmpreqArg1 := xxRouteVars["arg1"]
		{
			var err error
			reqArg1, err = strconv.Atoi(xxTmpreqArg1)

			if err != nil {

				t.Log.Handle(w, r, err, "route", "error", "RestReq", "GetConvertedToInt")
				http.Error(w, err.Error(), http.StatusInternalServerError)

				return
			}

		}

	} else if _, ok := xxURLValues["arg1"]; ok {
		xxTmpreqArg1 := xxURLValues.Get("arg1")
		{
			var err error
			reqArg1, err = strconv.Atoi(xxTmpreqArg1)

			if err != nil {

				t.Log.Handle(w, r, err, "get", "error", "RestReq", "GetConvertedToInt")
				http.Error(w, err.Error(), http.StatusInternalServerError)

				return
			}

		}

	} else if _, ok := r.Form["arg1"]; ok {
		xxTmpreqArg1 := r.FormValue("arg1")
		{
			var err error
			reqArg1, err = strconv.Atoi(xxTmpreqArg1)

			if err != nil {

				t.Log.Handle(w, r, err, "form", "error", "RestReq", "GetConvertedToInt")
				http.Error(w, err.Error(), http.StatusInternalServerError)

				return
			}

		}

	}

	t.embed.GetConvertedToInt(reqArg1)
	w.WriteHeader(200)

	t.Log.Handle(w, r, nil, "end", "RestReq", "GetConvertedToInt")
}

// GetConvertedToBool invoke Req.GetConvertedToBool using the request body as a json payload.
// GetConvertedToBool ...
func (t *RestReq) GetConvertedToBool(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RestReq", "GetConvertedToBool")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RestReq", "GetConvertedToBool")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}

	xxRouteVars := mux.Vars(r)

	xxURLValues := r.URL.Query()
	var reqArg1 bool
	if _, ok := xxRouteVars["arg1"]; ok {
		xxTmpreqArg1 := xxRouteVars["arg1"]
		{
			var err error
			reqArg1, err = strconv.ParseBool(xxTmpreqArg1)

			if err != nil {

				t.Log.Handle(w, r, err, "route", "error", "RestReq", "GetConvertedToBool")
				http.Error(w, err.Error(), http.StatusInternalServerError)

				return
			}

		}

	} else if _, ok := xxURLValues["arg1"]; ok {
		xxTmpreqArg1 := xxURLValues.Get("arg1")
		{
			var err error
			reqArg1, err = strconv.ParseBool(xxTmpreqArg1)

			if err != nil {

				t.Log.Handle(w, r, err, "get", "error", "RestReq", "GetConvertedToBool")
				http.Error(w, err.Error(), http.StatusInternalServerError)

				return
			}

		}

	} else if _, ok := r.Form["arg1"]; ok {
		xxTmpreqArg1 := r.FormValue("arg1")
		{
			var err error
			reqArg1, err = strconv.ParseBool(xxTmpreqArg1)

			if err != nil {

				t.Log.Handle(w, r, err, "form", "error", "RestReq", "GetConvertedToBool")
				http.Error(w, err.Error(), http.StatusInternalServerError)

				return
			}

		}

	}

	t.embed.GetConvertedToBool(reqArg1)
	w.WriteHeader(200)

	t.Log.Handle(w, r, nil, "end", "RestReq", "GetConvertedToBool")
}

// GetMaybe invoke Req.GetMaybe using the request body as a json payload.
// GetMaybe ...
func (t *RestReq) GetMaybe(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RestReq", "GetMaybe")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RestReq", "GetMaybe")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}

	xxRouteVars := mux.Vars(r)

	xxURLValues := r.URL.Query()
	var reqArg1 *string
	if _, ok := xxRouteVars["arg1"]; ok {
		xxTmpreqArg1 := xxRouteVars["arg1"]
		reqArg1 = &xxTmpreqArg1
	} else if _, ok := xxURLValues["arg1"]; ok {
		xxTmpreqArg1 := xxURLValues.Get("arg1")
		reqArg1 = &xxTmpreqArg1
	} else if _, ok := r.Form["arg1"]; ok {
		xxTmpreqArg1 := r.FormValue("arg1")
		reqArg1 = &xxTmpreqArg1
	}

	t.embed.GetMaybe(reqArg1)
	w.WriteHeader(200)

	t.Log.Handle(w, r, nil, "end", "RestReq", "GetMaybe")
}

// RestReqDescriptor describe a *RestReq
type RestReqDescriptor struct {
	ggt.TypeDescriptor
	about                    *RestReq
	methodGetOne             *ggt.MethodDescriptor
	methodGetMany            *ggt.MethodDescriptor
	methodGetConvertedToInt  *ggt.MethodDescriptor
	methodGetConvertedToBool *ggt.MethodDescriptor
	methodGetMaybe           *ggt.MethodDescriptor
}

// NewRestReqDescriptor describe a *RestReq
func NewRestReqDescriptor(about *RestReq) *RestReqDescriptor {
	ret := &RestReqDescriptor{about: about}
	ret.methodGetOne = &ggt.MethodDescriptor{
		Name:    "GetOne",
		Handler: about.GetOne,
		Route:   "GetOne",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetOne)
	ret.methodGetMany = &ggt.MethodDescriptor{
		Name:    "GetMany",
		Handler: about.GetMany,
		Route:   "GetMany",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetMany)
	ret.methodGetConvertedToInt = &ggt.MethodDescriptor{
		Name:    "GetConvertedToInt",
		Handler: about.GetConvertedToInt,
		Route:   "GetConvertedToInt",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetConvertedToInt)
	ret.methodGetConvertedToBool = &ggt.MethodDescriptor{
		Name:    "GetConvertedToBool",
		Handler: about.GetConvertedToBool,
		Route:   "GetConvertedToBool",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetConvertedToBool)
	ret.methodGetMaybe = &ggt.MethodDescriptor{
		Name:    "GetMaybe",
		Handler: about.GetMaybe,
		Route:   "GetMaybe",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetMaybe)
	return ret
}

// GetOne returns a MethodDescriptor
func (t *RestReqDescriptor) GetOne() *ggt.MethodDescriptor { return t.methodGetOne }

// GetMany returns a MethodDescriptor
func (t *RestReqDescriptor) GetMany() *ggt.MethodDescriptor { return t.methodGetMany }

// GetConvertedToInt returns a MethodDescriptor
func (t *RestReqDescriptor) GetConvertedToInt() *ggt.MethodDescriptor {
	return t.methodGetConvertedToInt
}

// GetConvertedToBool returns a MethodDescriptor
func (t *RestReqDescriptor) GetConvertedToBool() *ggt.MethodDescriptor {
	return t.methodGetConvertedToBool
}

// GetMaybe returns a MethodDescriptor
func (t *RestReqDescriptor) GetMaybe() *ggt.MethodDescriptor { return t.methodGetMaybe }
