package capable

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	json "encoding/json"
	ggt "github.com/mh-cbon/ggt/lib"
	"io"
	"net/http"
	"strconv"
)

var xxe95288e83d8cab7b0beba9ee37d79e43f68db57d = strconv.Atoi
var xxcdce08ad494f1315b1ae677a75ff9a333d2f7a36 = io.Copy
var xx311af88f99f154b2659e5478d5663c515febcae5 = http.StatusOK

// RPCPost is an httper of Post.
// Post ...
type RPCPost struct {
	embed Post
	Log   ggt.HTTPLogger
}

// NewRPCPost constructs an httper of Post
func NewRPCPost(embed Post) *RPCPost {
	ret := &RPCPost{
		embed: embed,
		Log:   &ggt.VoidLog{},
	}
	ret.Log.Handle(nil, nil, nil, "constructor", "RPCPost")
	return ret
}

// GetOne invoke Post.GetOne using the request body as a json payload.
// GetOne ...
func (t *RPCPost) GetOne(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCPost", "GetOne")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RPCPost", "GetOne")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}
	input := struct {
		Arg0 string
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCPost", "GetOne")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetOne(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCPost", "GetOne")
}

// GetMany invoke Post.GetMany using the request body as a json payload.
// GetMany ...
func (t *RPCPost) GetMany(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCPost", "GetMany")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RPCPost", "GetMany")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}
	input := struct {
		Arg0 string
		Arg1 string
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCPost", "GetMany")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetMany(input.Arg0, input.Arg1)

	t.Log.Handle(w, r, nil, "end", "RPCPost", "GetMany")
}

// GetConvertedToInt invoke Post.GetConvertedToInt using the request body as a json payload.
// GetConvertedToInt ...
func (t *RPCPost) GetConvertedToInt(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCPost", "GetConvertedToInt")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RPCPost", "GetConvertedToInt")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}
	input := struct {
		Arg0 int
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCPost", "GetConvertedToInt")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetConvertedToInt(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCPost", "GetConvertedToInt")
}

// GetConvertedToBool invoke Post.GetConvertedToBool using the request body as a json payload.
// GetConvertedToBool ...
func (t *RPCPost) GetConvertedToBool(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCPost", "GetConvertedToBool")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RPCPost", "GetConvertedToBool")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}
	input := struct {
		Arg0 bool
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCPost", "GetConvertedToBool")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetConvertedToBool(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCPost", "GetConvertedToBool")
}

// GetConvertedToSlice invoke Post.GetConvertedToSlice using the request body as a json payload.
// GetConvertedToSlice ...
func (t *RPCPost) GetConvertedToSlice(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCPost", "GetConvertedToSlice")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RPCPost", "GetConvertedToSlice")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}
	input := struct {
		Arg0 []bool
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCPost", "GetConvertedToSlice")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetConvertedToSlice(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCPost", "GetConvertedToSlice")
}

// GetMaybe invoke Post.GetMaybe using the request body as a json payload.
// GetMaybe ...
func (t *RPCPost) GetMaybe(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RPCPost", "GetMaybe")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RPCPost", "GetMaybe")
			http.Error(w, err.Error(), http.StatusInternalServerError)

			return
		}

	}
	input := struct {
		Arg0 *string
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)

	if decErr != nil {

		t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RPCPost", "GetMaybe")
		http.Error(w, decErr.Error(), http.StatusInternalServerError)

		return
	}

	t.embed.GetMaybe(input.Arg0)

	t.Log.Handle(w, r, nil, "end", "RPCPost", "GetMaybe")
}

// RPCPostDescriptor describe a *RPCPost
type RPCPostDescriptor struct {
	ggt.TypeDescriptor
	about                     *RPCPost
	methodGetOne              *ggt.MethodDescriptor
	methodGetMany             *ggt.MethodDescriptor
	methodGetConvertedToInt   *ggt.MethodDescriptor
	methodGetConvertedToBool  *ggt.MethodDescriptor
	methodGetConvertedToSlice *ggt.MethodDescriptor
	methodGetMaybe            *ggt.MethodDescriptor
}

// NewRPCPostDescriptor describe a *RPCPost
func NewRPCPostDescriptor(about *RPCPost) *RPCPostDescriptor {
	ret := &RPCPostDescriptor{about: about}
	ret.methodGetOne = &ggt.MethodDescriptor{
		Name:    "GetOne",
		Handler: about.GetOne,
		Route:   "GetOne",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetOne)
	ret.methodGetMany = &ggt.MethodDescriptor{
		Name:    "GetMany",
		Handler: about.GetMany,
		Route:   "GetMany",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetMany)
	ret.methodGetConvertedToInt = &ggt.MethodDescriptor{
		Name:    "GetConvertedToInt",
		Handler: about.GetConvertedToInt,
		Route:   "GetConvertedToInt",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetConvertedToInt)
	ret.methodGetConvertedToBool = &ggt.MethodDescriptor{
		Name:    "GetConvertedToBool",
		Handler: about.GetConvertedToBool,
		Route:   "GetConvertedToBool",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetConvertedToBool)
	ret.methodGetConvertedToSlice = &ggt.MethodDescriptor{
		Name:    "GetConvertedToSlice",
		Handler: about.GetConvertedToSlice,
		Route:   "GetConvertedToSlice",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetConvertedToSlice)
	ret.methodGetMaybe = &ggt.MethodDescriptor{
		Name:    "GetMaybe",
		Handler: about.GetMaybe,
		Route:   "GetMaybe",
		Methods: []string{"GET"},
	}
	ret.TypeDescriptor.Register(ret.methodGetMaybe)
	return ret
}

// GetOne returns a MethodDescriptor
func (t *RPCPostDescriptor) GetOne() *ggt.MethodDescriptor { return t.methodGetOne }

// GetMany returns a MethodDescriptor
func (t *RPCPostDescriptor) GetMany() *ggt.MethodDescriptor { return t.methodGetMany }

// GetConvertedToInt returns a MethodDescriptor
func (t *RPCPostDescriptor) GetConvertedToInt() *ggt.MethodDescriptor {
	return t.methodGetConvertedToInt
}

// GetConvertedToBool returns a MethodDescriptor
func (t *RPCPostDescriptor) GetConvertedToBool() *ggt.MethodDescriptor {
	return t.methodGetConvertedToBool
}

// GetConvertedToSlice returns a MethodDescriptor
func (t *RPCPostDescriptor) GetConvertedToSlice() *ggt.MethodDescriptor {
	return t.methodGetConvertedToSlice
}

// GetMaybe returns a MethodDescriptor
func (t *RPCPostDescriptor) GetMaybe() *ggt.MethodDescriptor { return t.methodGetMaybe }
