package login

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	"bytes"
	json "encoding/json"
	"errors"
	"net/http"
)

// RPCClient is an http-clienter of Controller.
// Controller of user login
type RPCClient struct {
	client *http.Client
}

// NewRPCClient constructs an http-clienter of Controller
func NewRPCClient(client *http.Client) *RPCClient {
	if client == nil {
		client = http.DefaultClient
	}
	ret := &RPCClient{
		client: client,
	}
	return ret
}

var xx02eba78324b686eb8959e353dd12d0255ed0c9b9 = http.StatusOK

// Login constructs a request to Login
func (t RPCClient) Login(postLogin string, postPassword string) (*User, *http.Cookie, error) {
	var reqBody bytes.Buffer

	{
		input := struct {
			Arg0 string
			Arg1 string
		}{
			Arg0: postLogin,
			Arg1: postPassword,
		}
		encErr := json.NewEncoder(&reqBody).Encode(&input)
		if encErr != nil {
			return nil, nil, errors.New("todo")
		}

	}
	finalURL := "/Login"
	req, reqErr := http.NewRequest("POST", finalURL, &reqBody)
	if reqErr != nil {
		return nil, nil, errors.New("todo")
	}

	res, resErr := t.client.Do(req)
	if resErr != nil {
		return nil, nil, errors.New("todo")
	}

	output := struct {
		Arg0 *User
		Arg1 *http.Cookie
		Arg2 error
	}{}
	{
		decErr := json.NewDecoder(res.Body).Decode(&output)
		if decErr != nil {
			return nil, nil, errors.New("todo")
		}

	}

	return output.Arg0, output.Arg1, output.Arg2

}

// Logout constructs a request to Logout
func (t RPCClient) Logout(cookieLogin string) (*http.Cookie, error) {
	var reqBody bytes.Buffer

	{
		input := struct {
			Arg0 string
		}{
			Arg0: cookieLogin,
		}
		encErr := json.NewEncoder(&reqBody).Encode(&input)
		if encErr != nil {
			return nil, errors.New("todo")
		}

	}
	finalURL := "/Logout"
	req, reqErr := http.NewRequest("POST", finalURL, &reqBody)
	if reqErr != nil {
		return nil, errors.New("todo")
	}

	res, resErr := t.client.Do(req)
	if resErr != nil {
		return nil, errors.New("todo")
	}

	output := struct {
		Arg0 *http.Cookie
		Arg1 error
	}{}
	{
		decErr := json.NewDecoder(res.Body).Decode(&output)
		if decErr != nil {
			return nil, errors.New("todo")
		}

	}

	return output.Arg0, output.Arg1

}

// Create constructs a request to Create
func (t RPCClient) Create(postLogin string, postPassword string) (*User, error) {
	var reqBody bytes.Buffer

	{
		input := struct {
			Arg0 string
			Arg1 string
		}{
			Arg0: postLogin,
			Arg1: postPassword,
		}
		encErr := json.NewEncoder(&reqBody).Encode(&input)
		if encErr != nil {
			return nil, errors.New("todo")
		}

	}
	finalURL := "/Create"
	req, reqErr := http.NewRequest("POST", finalURL, &reqBody)
	if reqErr != nil {
		return nil, errors.New("todo")
	}

	res, resErr := t.client.Do(req)
	if resErr != nil {
		return nil, errors.New("todo")
	}

	output := struct {
		Arg0 *User
		Arg1 error
	}{}
	{
		decErr := json.NewDecoder(res.Body).Decode(&output)
		if decErr != nil {
			return nil, errors.New("todo")
		}

	}

	return output.Arg0, output.Arg1

}
