package tomate

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	json "encoding/json"
	"github.com/gorilla/mux"
	ggt "github.com/mh-cbon/ggt/lib"
	"io"
	"net/http"
	"strconv"
)

var xxc52d52149b9b88887c5b162b670197217023167c = strconv.Atoi
var xxdddd5c3cff35fd51b960096f826c90c635b524c8 = io.Copy
var xx50b52bbd0311cf9ec8e406218f58ce92f00e2679 = http.StatusOK

// RestController is an httper of Controller.
// Controller of tomatoes.
type RestController struct {
	embed Controller
	Log   ggt.HTTPLogger
}

// NewRestController constructs an httper of Controller
func NewRestController(embed Controller) *RestController {
	ret := &RestController{
		embed: embed,
		Log:   &ggt.VoidLog{},
	}
	ret.Log.Handle(nil, nil, nil, "constructor", "RestController")
	return ret
}

// GetByID invoke Controller.GetByID using the request body as a json payload.
// GetByID read the Tomate of given ID
//
// @route /read/{id:[0-9]+}
func (t *RestController) GetByID(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RestController", "GetByID")

	xxRouteVars := mux.Vars(r)
	var routeID string
	if _, ok := xxRouteVars["id"]; ok {
		xxTmprouteID := xxRouteVars["id"]
		routeID = xxTmprouteID
	}

	jsonResBody, err := t.embed.GetByID(routeID)

	if err != nil {

		t.Log.Handle(w, r, err, "business", "error", "RestController", "GetByID")
		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.Log.Handle(w, r, encErr, "res", "json", "encode", "error", "RestController", "GetByID")
			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

	t.Log.Handle(w, r, nil, "end", "RestController", "GetByID")
}

// Create invoke Controller.Create using the request body as a json payload.
// Create a new Tomate
//
// @route /create
func (t *RestController) Create(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RestController", "Create")

	{
		err := r.ParseForm()

		if err != nil {

			t.Log.Handle(w, r, err, "parseform", "error", "RestController", "Create")
			t.embed.Finalizer(w, r, err)

			return
		}

	}
	var postColor *string
	if _, ok := r.Form["color"]; ok {
		xxTmppostColor := r.FormValue("color")
		postColor = &xxTmppostColor
	}

	jsonResBody, err := t.embed.Create(postColor)

	if err != nil {

		t.Log.Handle(w, r, err, "business", "error", "RestController", "Create")
		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.Log.Handle(w, r, encErr, "res", "json", "encode", "error", "RestController", "Create")
			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

	t.Log.Handle(w, r, nil, "end", "RestController", "Create")
}

// Update invoke Controller.Update using the request body as a json payload.
// Update an existing Tomate
//
// @route /write/{id:[0-9]+}
func (t *RestController) Update(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RestController", "Update")

	xxRouteVars := mux.Vars(r)
	var routeID string
	if _, ok := xxRouteVars["id"]; ok {
		xxTmprouteID := xxRouteVars["id"]
		routeID = xxTmprouteID
	}
	var jsonReqBody *Tomate
	{
		jsonReqBody = &Tomate{}
		decErr := json.NewDecoder(r.Body).Decode(jsonReqBody)

		if decErr != nil {

			t.Log.Handle(w, r, decErr, "req", "json", "decode", "error", "RestController", "Update")
			t.embed.Finalizer(w, r, decErr)

			return
		}

		defer r.Body.Close()
	}

	jsonResBody, err := t.embed.Update(routeID, jsonReqBody)

	if err != nil {

		t.Log.Handle(w, r, err, "business", "error", "RestController", "Update")
		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.Log.Handle(w, r, encErr, "res", "json", "encode", "error", "RestController", "Update")
			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

	t.Log.Handle(w, r, nil, "end", "RestController", "Update")
}

// Remove invoke Controller.Remove using the request body as a json payload.
// Remove an existing Tomate
//
// @route /remove/{id:[0-9]+}
func (t *RestController) Remove(w http.ResponseWriter, r *http.Request) {
	t.Log.Handle(w, r, nil, "begin", "RestController", "Remove")

	xxRouteVars := mux.Vars(r)
	var routeID string
	if _, ok := xxRouteVars["id"]; ok {
		xxTmprouteID := xxRouteVars["id"]
		routeID = xxTmprouteID
	}

	jsonResBody, err := t.embed.Remove(routeID)

	if err != nil {

		t.Log.Handle(w, r, err, "business", "error", "RestController", "Remove")
		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.Log.Handle(w, r, encErr, "res", "json", "encode", "error", "RestController", "Remove")
			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

	t.Log.Handle(w, r, nil, "end", "RestController", "Remove")
}

// RestControllerDescriptor describe a *RestController
type RestControllerDescriptor struct {
	ggt.TypeDescriptor
	about         *RestController
	methodGetByID *ggt.MethodDescriptor
	methodCreate  *ggt.MethodDescriptor
	methodUpdate  *ggt.MethodDescriptor
	methodRemove  *ggt.MethodDescriptor
}

// NewRestControllerDescriptor describe a *RestController
func NewRestControllerDescriptor(about *RestController) *RestControllerDescriptor {
	ret := &RestControllerDescriptor{about: about}
	ret.methodGetByID = &ggt.MethodDescriptor{
		Name:    "GetByID",
		Handler: about.GetByID,
		Route:   "/read/{id:[0-9]+}",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGetByID)
	ret.methodCreate = &ggt.MethodDescriptor{
		Name:    "Create",
		Handler: about.Create,
		Route:   "/create",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodCreate)
	ret.methodUpdate = &ggt.MethodDescriptor{
		Name:    "Update",
		Handler: about.Update,
		Route:   "/write/{id:[0-9]+}",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodUpdate)
	ret.methodRemove = &ggt.MethodDescriptor{
		Name:    "Remove",
		Handler: about.Remove,
		Route:   "/remove/{id:[0-9]+}",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodRemove)
	return ret
}

// GetByID returns a MethodDescriptor
func (t *RestControllerDescriptor) GetByID() *ggt.MethodDescriptor { return t.methodGetByID }

// Create returns a MethodDescriptor
func (t *RestControllerDescriptor) Create() *ggt.MethodDescriptor { return t.methodCreate }

// Update returns a MethodDescriptor
func (t *RestControllerDescriptor) Update() *ggt.MethodDescriptor { return t.methodUpdate }

// Remove returns a MethodDescriptor
func (t *RestControllerDescriptor) Remove() *ggt.MethodDescriptor { return t.methodRemove }
