package tomate

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	"errors"
	"net/http"
)

// RPCClient is an http-clienter of Controller.
// Controller of tomatoes.
type RPCClient struct {
	Base   string
	Client *http.Client
}

// NewRPCClient constructs an http-clienter of Controller
func NewRPCClient() *RPCClient {
	ret := &RPCClient{
		Client: http.DefaultClient,
	}
	return ret
}

// GetByID constructs a request to GetByID
func (t RPCClient) GetByID(getID string) (*Tomate, error) {
	return nil, errors.New("todo")
}

// Create constructs a request to Create
func (t RPCClient) Create(postColor *string) (*Tomate, error) {
	return nil, errors.New("todo")
}

// Update constructs a request to Update
func (t RPCClient) Update(routeID string, jsonReqBody *Tomate) (*Tomate, error) {
	return nil, errors.New("todo")
}

// Finalizer constructs a request to Finalizer
func (t RPCClient) Finalizer(w http.ResponseWriter, r *http.Request, err error) {
	return nil, errors.New("todo")
}
