package tomate

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	json "encoding/json"
	"fmt"
	"github.com/gorilla/mux"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// RestClient is an http-clienter of Controller.
// Controller of tomatoes.
type RestClient struct {
	router *mux.Router
	Base   string
	Client *http.Client
}

// NewRestClient constructs an http-clienter of Controller
func NewRestClient(router *mux.Router) *RestClient {
	ret := &RestClient{
		router: router,
		Client: http.DefaultClient,
	}
	return ret
}

// Update constructs a request to /write/{id:[0-9]+}
func (t RestClient) Update(routeID string, jsonReqBody *Tomate) (jsonResBody *Tomate, err error) {
	// var ret *http.Request
	var body io.ReadWriter
	// var err error

	{
		var b bytes.Buffer
		body = &b
		encErr := json.NewEncoder(body).Encode(jsonReqBody)
		if encErr != nil {
			return jsonResBody, err
		}

	}
	surl := "/write/{id:[0-9]+}"
	surl = strings.Replace(surl, "{id:[0-9]+}", fmt.Sprintf("%v", routeID), 1)
	url, URLerr := url.ParseRequestURI(surl)
	if URLerr != nil {
		return jsonResBody, err
	}
	finalURL := url.String()
	finalURL = fmt.Sprintf("%v%v", t.Base, finalURL)

	req, reqErr := http.NewRequest("GET", finalURL, body)
	if reqErr != nil {
		return jsonResBody, err
	}

	{
		res, resErr := t.Client.Do(req)
		if resErr != nil {
			return jsonResBody, err
		}

		decErr := json.NewDecoder(res.Body).Decode(jsonResBody)
		if decErr != nil {
			return jsonResBody, err
		}

	}

	return jsonResBody, err
}
