package tomate

// file generated by
// github.com/mh-cbon/ggt
// do not edit

import (
	json "encoding/json"
	"github.com/gorilla/mux"
	ggt "github.com/mh-cbon/ggt/lib"
	"io"
	"net/http"
	"strconv"
)

var xxStrconvAtoi = strconv.Atoi
var xxIoCopy = io.Copy
var xxHTTPOk = http.StatusOK

// RestController is an httper of Controller.
// Controller of tomatoes.
type RestController struct {
	embed Controller
}

// NewRestController constructs an httper of Controller
func NewRestController(embed Controller) *RestController {
	ret := &RestController{
		embed: embed,
	}
	return ret
}

// GetByID invoke Controller.GetByID using the request body as a json payload.
// GetByID read the Tomate of given ID
func (t *RestController) GetByID(w http.ResponseWriter, r *http.Request) {

	xxURLValues := r.URL.Query()
	var getID string
	if _, ok := xxURLValues["id"]; ok {
		xxTmpgetID := xxURLValues.Get("id")
		getID = xxTmpgetID
	}

	jsonResBody, err := t.embed.GetByID(getID)

	if err != nil {

		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

}

// Create invoke Controller.Create using the request body as a json payload.
// Create a new Tomate
func (t *RestController) Create(w http.ResponseWriter, r *http.Request) {

	{
		err := r.ParseForm()

		if err != nil {

			t.embed.Finalizer(w, r, err)

			return
		}

	}
	var postColor *string
	if _, ok := r.Form["color"]; ok {
		xxTmppostColor := r.FormValue("color")
		postColor = &xxTmppostColor
	}

	jsonResBody, err := t.embed.Create(postColor)

	if err != nil {

		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

}

// Update invoke Controller.Update using the request body as a json payload.
// Update an existing Tomate
//
// @route /write/{id:[0-9]+}
func (t *RestController) Update(w http.ResponseWriter, r *http.Request) {

	xxRouteVars := mux.Vars(r)
	var routeID string
	if _, ok := xxRouteVars["id"]; ok {
		xxTmprouteID := xxRouteVars["id"]
		routeID = xxTmprouteID
	}
	var jsonReqBody *Tomate
	{
		jsonReqBody = &Tomate{}
		decErr := json.NewDecoder(r.Body).Decode(jsonReqBody)

		if decErr != nil {

			t.embed.Finalizer(w, r, decErr)

			return
		}

		defer r.Body.Close()
	}

	jsonResBody, err := t.embed.Update(routeID, jsonReqBody)

	if err != nil {

		t.embed.Finalizer(w, r, err)

		return
	}

	{
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		encErr := json.NewEncoder(w).Encode(jsonResBody)

		if encErr != nil {

			t.embed.Finalizer(w, r, encErr)

			return
		}

	}

}

// RestControllerDescriptor describe a *RestController
type RestControllerDescriptor struct {
	ggt.TypeDescriptor
	about         *RestController
	methodGetByID *ggt.MethodDescriptor
	methodCreate  *ggt.MethodDescriptor
	methodUpdate  *ggt.MethodDescriptor
}

// NewRestControllerDescriptor describe a *RestController
func NewRestControllerDescriptor(about *RestController) *RestControllerDescriptor {
	ret := &RestControllerDescriptor{about: about}
	ret.methodGetByID = &ggt.MethodDescriptor{
		Name:    "GetByID",
		Handler: about.GetByID,
		Route:   "GetByID",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodGetByID)
	ret.methodCreate = &ggt.MethodDescriptor{
		Name:    "Create",
		Handler: about.Create,
		Route:   "Create",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodCreate)
	ret.methodUpdate = &ggt.MethodDescriptor{
		Name:    "Update",
		Handler: about.Update,
		Route:   "/write/{id:[0-9]+}",
		Methods: []string{},
	}
	ret.TypeDescriptor.Register(ret.methodUpdate)
	return ret
}

// GetByID returns a MethodDescriptor
func (t *RestControllerDescriptor) GetByID() *ggt.MethodDescriptor { return t.methodGetByID }

// Create returns a MethodDescriptor
func (t *RestControllerDescriptor) Create() *ggt.MethodDescriptor { return t.methodCreate }

// Update returns a MethodDescriptor
func (t *RestControllerDescriptor) Update() *ggt.MethodDescriptor { return t.methodUpdate }
